spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./data/exampleSns;MODE=MySQL
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

