spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./data/exampleSns;MODE=MySQL;SCHEMA=PUBLIC
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        use_sql_comments: true
        format_sql: true
jwt:
  secretKey: liilnsnsilnexampleilnnegsecretilnkeyilnnegilnlgeiilnjwtilnexllii2mpleSnsilnliiln
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

